image: registry.gitlab.com/dune-archiso/images/dune-archiso-yay

tasks:
  - name: Clone a flexible finite element toolkit
    env:
      REPO: "https://kosinus.math.uni-magdeburg.de/gascoigne/gascoignelib.git"
      PACKAGES: "openmp eigen suitesparse cmake"
    command: |
      yay -Sy --noconfirm
      yay -S metis ${PACKAGES} --noconfirm
      [ -d gascoignelib ] || git clone -q ${REPO}
      cmake -S gascoignelib -B build -DBUILD_TESTS=ON -DWITH_THREADS=ON -DWITH_UMFPACK=ON
      cmake --build build --target all
